# Paths to yolo training and evaluation folders
train: data/yolo/images/train
val: data/yolo/images/val

# Number of classes
nc: 2

# Class names, in order of their class IDs
names:
  0: fullart
  1: standard
