yolo_datagen:
  source_dir: "images/cards"
  background_dir: "images/backgrounds"
  output_img_dir: "data/yolo/images/train"
  output_label_dir: "data/yolo/labels/train"
  val_split: 0.2
  allowed_ext: [".png", ".jpg", ".jpeg"]
  variants_per: 100

cnn_datagen:
  source_dir: "images/cards"
  output_train_dir: "data/cnn/train"
  output_val_dir: "data/cnn/val"
  val_split: 0.2
  allowed_ext: [".png", ".jpg", ".jpeg"]
  variants_per: 120
  random_seed: 132
